### ISSUE TITLE
dataset availability

### ISSUE THREAD

**Issue by qgeissmann** [stasys-hub/Collembola_AI#5]
Hi, thank you so much for such a great resource. I really enjoyed reading your paper. I was wondering if you had made the annotated or raw images available, and under what conditions. I am compiling datasets of arthropods for instance segmentation...
Many thanks!

**Comment by stasys-hub** [comment]
That's nice to hear. 
You can find the community dataset on [kaggle](https://www.kaggle.com/datasets/6684ca6ba3f391356b2435fe1f80160923e9d92b2fd03c9d69dc88286c785d23).
There should also be a zenodo Dataset associated with the paper, but as far as I remeber they should be identical.

**Comment by qgeissmann** [comment]
Thanks for the very quick answer! Closing the issue then :).
